In [ ]:
# https://www.youtube.com/watch?v=C10KmAbCW6A&list=PLxgDUj5eygKnSd4MYHIuAC7E3VEPm_WLO&index=5

In [1]:
import numpy as np

In [2]:
L = [1, 2, 3]

In [3]:
A = np.array([1, 2, 3])

In [4]:
# print list L
for e in L:
    print(e)

1
2
3


In [5]:
# print array A
for e in A:
    print(e)

1
2
3


In [6]:
# works the same
# let's add a new item
L.append(4)
L

[1, 2, 3, 4]

In [7]:
# let's try that with the NumPy array
A.append(4)
# nope, error, size of array is fixed; we need to instantiate a new array and copy values over

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [8]:
# CONCATENATE two lists
L + [5]

[1, 2, 3, 4, 5]

In [9]:
A + np.array([4])

array([5, 6, 7])

In [ ]:
# added 4 element-wise
# called BROADCASTING; in maths this would be an illegal operation
# np is about maths, so we eleicited a mathematical operation

In [10]:
# let's try it differently
print(A)
A + np.array([4, 5, 6])

[1 2 3]


array([5, 7, 9])

In [11]:
# now it won't be able to BROADCAST (add 4 or 5 to the last element?)
A + np.array([4, 5])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [12]:
A + np.array([4])

array([5, 6, 7])

In [13]:
# (scalar) multiplication
2 * A

array([2, 4, 6])

In [14]:
2 * L
# a LIST gets REPEATED
# an ARRAY gets MULTIPLIED

[1, 2, 3, 4, 1, 2, 3, 4]

In [15]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [16]:
# error
2.5 * L

TypeError: can't multiply sequence by non-int of type 'float'

In [17]:
# non-integer multiplication
2.5 * A

array([2.5, 5. , 7.5])

In [18]:
# lists for vector/matrix multiplication is complicated
L2 = []
for e in L:
    L2.append(e + 3)
L2

[4, 5, 6, 7]

In [ ]:
# shorter code using LIST COMPREHENSION
L2 = [e + 3 for e in L]

In [19]:
# square all elements
L**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [21]:
L2 = []
for e in L:
    L2.append(e**2)
L2

[1, 4, 9, 16]

In [22]:
# in numpy, syntax is MUCH better, many operations are element-wise
A**2

array([1, 4, 9])

In [24]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [25]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [26]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
# hyperbolic tangent, often used in ML
np.tanh(A)

In [ ]:
# see documentation for more functions that are available

> Lists are **generic datastructures** while NumPy arrays exist **to do maths**.