In [ ]:
# https://www.youtube.com/watch?v=IXAeTyT3kBM&list=PLxgDUj5eygKnSd4MYHIuAC7E3VEPm_WLO&index=8
# Matrices

In [1]:
# numpy object numpy.matrix not recommended to use
# matrix must be 2-dimensional, np.arrays can be any shape
import numpy as np

In [2]:
# cosy: array of array or list of lists
L = [   [1, 2],
        [3, 4]]

In [3]:
# array access: rows come first by convention
L[0]

[1, 2]

In [4]:
L[0][1]

2

In [7]:
# in NumPy
# ionitialise array by passing in a list
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [8]:
# formatted like it was a matrix
# access like before
A[0][1]

2

In [9]:
# but also with easier syntax in R style
A[0,1]

2

In [10]:
# select column 1 of all rows using the COLON operator
A[:,1]

array([2, 4])

In [11]:
# transpose it (A^T)
A.T

array([[1, 3],
       [2, 4]])

In [12]:
# apply a function to A
# gets applied ELEMENT-WISE
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [13]:
# does this work with lists?
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [ ]:
# omg, it works!!!

In [14]:
# matrix multiplication
# 2 x 3
B = np.array([[1,2,3],[4,5,6]])

In [15]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [16]:
# A * B would be element-wise multiplication, as A and B don't have the same shape it wouldn't work

In [17]:
# if inner dimensions don't match...
A.dot(B.T)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [18]:
# determinant
np.linalg.det(A)

-2.0000000000000004

In [19]:
# inverse
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [20]:
# check: A^-1 * A = I
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [21]:
# inversion is compuztationally inaccurate

In [22]:
# trace
np.trace(A)

5

In [23]:
# diagonal elements
np.diag(A)

array([1, 4])

In [24]:
# on a vector...
np.diag([1, 4])

array([[1, 0],
       [0, 4]])

In [25]:
# it's overloaded
# in        out
# matrix    vector
# vector    matrix

In [26]:
# eigenvalues/vectors
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [27]:
# eigenvalues
# eigenvectors, organised into a matrix

In [28]:
lam, V = np.linalg.eig(A)

In [30]:
# eigenvectors are column vectors in V
V[:,0] * lam[0] == A @ V[:,0]

array([ True, False])

In [32]:
# second is false b/c of numeric i# second is false b/c of numeric inccuracies
V[:,0] * lam[0], A @ V[:,0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [33]:
np.allclose(V[:,0] * lam[0], A @ V[:,0])

True

In [36]:
np.allclose(
    V @ np.diag(lam),
    A @ V
)

True