In [2]:
# https://www.youtube.com/watch?v=WASuVuALYVE&list=PLxgDUj5eygKnSd4MYHIuAC7E3VEPm_WLO&index=10
# Generating data

# NNs need randomly initialised large matrices
# synthetic data to test algorithms to check how a model performs on our generated data we know the answer to

import numpy as np

In [3]:
# all-zeroes array
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
# you pass in the dimension of the array
# any numer: multiply scalar with ones
3 * np.ones((2,3))

array([[3., 3., 3.],
       [3., 3., 3.]])

In [6]:
# identity -> I but it's just one letter and therefore confusing
# --> same pronunciation --> eye function
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
# (pseudo) random numbers --> random module
np.random.random()

0.8245777689465151

In [9]:
np.random.random((2,3))

array([[0.28115244, 0.34250206, 0.5812974 ],
       [0.97260584, 0.6481125 , 0.59052605]])

In [10]:
# which distribution are the random numbers drawn from?
# uniform
# standard normal distribution --> Gaussian --> randn function
np.random.randn(2, 3)
# does not take a touple but just the dimensions as a list of integers

array([[ 1.0679606 ,  0.46119455, -0.91956657],
       [-0.71811413, -0.88089943, -1.14928064]])

In [11]:
# let's do some low-level stats
R = np.random.randn(10_000)
R.mean()

-0.007516379352044828

In [12]:
# top-level as well as an instance function
np.mean(R)

-0.007516379352044828

In [17]:
# variance
print(
    R.var(),
    np.var(R), sep="\n")

1.005350951558687
1.005350951558687


In [16]:
print(
    R.std(),
    np.std(R), sep="\n")

1.0026719062378715 1.0026719062378715


In [18]:
R = np.random.randn(10_000, 3)

In [24]:
R.mean(axis=0)

array([ 0.01337531, -0.00944926,  0.02181383])

In [25]:
R.mean(axis=0).shape

(3,)

In [26]:
R.mean(axis=1)

array([-0.5021831 ,  0.48960014, -0.17838357, ..., -0.14490095,
       -0.9194655 , -0.25656182])

In [27]:
R.mean(axis=1).shape

(10000,)

In [29]:
# rows:     records
# columns:  measures
# --> row is a vector of observations
# covariance --> cov function
np.cov(R)

array([[ 1.59447183,  1.07295379,  0.14361864, ..., -0.56563824,
        -0.0628617 ,  0.40826414],
       [ 1.07295379,  1.54454488, -1.20714618, ...,  0.52353572,
        -0.4076409 , -0.59689808],
       [ 0.14361864, -1.20714618,  2.07956659, ..., -1.48413649,
         0.57343612,  1.41838557],
       ...,
       [-0.56563824,  0.52353572, -1.48413649, ...,  1.19456157,
        -0.37929876, -1.10296587],
       [-0.0628617 , -0.4076409 ,  0.57343612, ..., -0.37929876,
         0.1647496 ,  0.37105096],
       [ 0.40826414, -0.59689808,  1.41838557, ..., -1.10296587,
         0.37105096,  1.02819011]])

In [32]:
np.cov(R).shape
# 10_000 by 10_000
# each column gets treated as a vector of observations
# this is not following the convention, but specific to NUMPY

(10000, 10000)

In [33]:
np.cov(R.T)

array([[ 0.98655186, -0.01095631, -0.00281281],
       [-0.01095631,  0.99006806,  0.01642548],
       [-0.00281281,  0.01642548,  0.99229486]])

In [34]:
np.cov(R.T).shape

(3, 3)

In [35]:
np.cov(R, rowvar=False)

array([[ 0.98655186, -0.01095631, -0.00281281],
       [-0.01095631,  0.99006806,  0.01642548],
       [-0.00281281,  0.01642548,  0.99229486]])

In [40]:
# randomly generate integers
np.random.randint(low=0, high=10, size=(2,10))
# low inclusive, high is exclusive, as usual for python

array([[4, 3, 1, 2, 3, 1, 6, 9, 8, 6],
       [2, 3, 3, 8, 5, 2, 7, 0, 3, 8]])

In [42]:
np.random.choice(10, size=(3, 3))
# replace

array([[8, 8, 4],
       [5, 5, 5],
       [4, 0, 5]])