In [1]:
# https://www.youtube.com/watch?v=VffpyOrVoPU&list=PLxgDUj5eygKnSd4MYHIuAC7E3VEPm_WLO&index=20
# select rows and columns
import pandas as pd

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/lazyprogrammer/machine_learning_examples/master/tf2.0/sbux.csv')

In [3]:
df[0,0]

KeyError: (0, 0)

In [4]:
# error :o omg
df.columns

Index(['date', 'open', 'high', 'low', 'close', 'volume', 'Name'], dtype='object')

In [7]:
df.columns = ['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Name']

In [8]:
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Name'], dtype='object')

In [9]:
df['Open']

0       27.920
1       28.260
2       28.000
3       28.230
4       27.765
         ...  
1254    56.280
1255    55.900
1256    55.530
1257    53.685
1258    55.080
Name: Open, Length: 1259, dtype: float64

In [10]:
df[['Open', 'Close']]

Open   Close
0     27.920  28.185
1     28.260  28.070
2     28.000  28.130
3     28.230  27.915
4     27.765  27.775
...      ...     ...
1254  56.280  56.000
1255  55.900  55.770
1256  55.530  54.690
1257  53.685  55.610
1258  55.080  54.460

[1259 rows x 2 columns]

In [11]:
type(df['Open'])

pandas.core.series.Series

In [12]:
type(df[['Open', 'Close']])

pandas.core.frame.DataFrame

In [13]:
# Series <-> DataFrame objects

In [14]:
# select a row?
df.iloc[0]

Date      2013-02-08
Open           27.92
High          28.325
Low            27.92
Close         28.185
Volume       7146296
Name            SBUX
Name: 0, dtype: object

In [15]:
# 0th row
df.loc[0]

Date      2013-02-08
Open           27.92
High          28.325
Low            27.92
Close         28.185
Volume       7146296
Name            SBUX
Name: 0, dtype: object

In [16]:
# iloc integer indices
# loc  indices can be names, i.e. rows can be named

In [17]:
df2 = pd.read_csv('sbux.csv', index_col='date')

In [18]:
df2.head()

open    high     low   close   volume  Name
date                                                     
2013-02-08  27.920  28.325  27.920  28.185  7146296  SBUX
2013-02-11  28.260  28.260  27.930  28.070  5457354  SBUX
2013-02-12  28.000  28.275  27.975  28.130  8665592  SBUX
2013-02-13  28.230  28.230  27.750  27.915  7022056  SBUX
2013-02-14  27.765  27.905  27.675  27.775  8899188  SBUX

In [19]:
# date is now printed boldly, as it's the index for the df

In [21]:
df2.loc['2013-02-11']

open        28.26
high        28.26
low         27.93
close       28.07
volume    5457354
Name         SBUX
Name: 2013-02-11, dtype: object

In [22]:
df[df['Open'] > 64]

Date   Open    High    Low  Close   Volume  Name
1087  2017-06-05  64.85  64.870  64.18  64.27  6809284  SBUX
1088  2017-06-06  64.22  64.350  64.05  64.16  5448439  SBUX
1089  2017-06-07  64.13  64.295  63.34  63.50  8364994  SBUX

In [23]:
df[df['Name'] != "SBUX"]

Empty DataFrame
Columns: [Date, Open, High, Low, Close, Volume, Name]
Index: []

In [24]:
# we pass in a boolean
df['Name'] != "SBUX"

0       False
1       False
2       False
3       False
4       False
        ...  
1254    False
1255    False
1256    False
1257    False
1258    False
Name: Name, Length: 1259, dtype: bool

In [25]:
type(df['Name'] != "SBUX")

pandas.core.series.Series

In [29]:
import numpy as np
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
A[A % 2 == 0]

array([0, 2, 4, 6, 8])

In [32]:
A % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [33]:
type(A % 2 == 0)

numpy.ndarray

In [34]:
# in ML we usually work w/ arrays of numbers, not w/ dataframes
# convert DataFrame -> np.array
df.values

array([['2013-02-08', 27.92, 28.325, ..., 28.185, 7146296, 'SBUX'],
       ['2013-02-11', 28.26, 28.26, ..., 28.07, 5457354, 'SBUX'],
       ['2013-02-12', 28.0, 28.275, ..., 28.13, 8665592, 'SBUX'],
       ...,
       ['2018-02-05', 55.53, 56.26, ..., 54.69, 16059955, 'SBUX'],
       ['2018-02-06', 53.685, 56.06, ..., 55.61, 17415065, 'SBUX'],
       ['2018-02-07', 55.08, 55.43, ..., 54.46, 13927022, 'SBUX']],
      dtype=object)

In [40]:
# dtype=object
A = df[['Open', 'Close']].values
A

array([[27.92 , 28.185],
       [28.26 , 28.07 ],
       [28.   , 28.13 ],
       ...,
       [55.53 , 54.69 ],
       [53.685, 55.61 ],
       [55.08 , 54.46 ]])

In [41]:
type(A)

numpy.ndarray

In [42]:
# save it to a file
smalldf = df[["Open", "Close"]]

In [43]:
smalldf.to_csv('output.csv')

In [44]:
!head output.csv

,Open,Close
0,27.92,28.185
1,28.26,28.07
2,28.0,28.13
3,28.23,27.915
4,27.765,27.775
5,27.805,27.17
6,27.18,27.225
7,27.3,26.655
8,26.535,26.675


In [45]:
# useless index column
smalldf.to_csv('output.csv', index=False)

In [46]:
!head output.csv

Open,Close
27.92,28.185
28.26,28.07
28.0,28.13
28.23,27.915
27.765,27.775
27.805,27.17
27.18,27.225
27.3,26.655
26.535,26.675


In [47]:
#!rm output.csv